name: WatchTestGen

options:
  bundleIdPrefix: com.example

targets:
  WatchTest:
    sources:
      - WatchTest
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      base:
        INFOPLIST_FILE: "WatchTestWatch Watch App/Info.plist"
    dependencies:
      - target: "WatchTestWatch Watch App"

  WatchTestWatch Watch App:
    platform: watchOS
    deploymentTarget: "9.0"
    type: application.watchapp2
    sources:
      - "WatchTestWatch Watch App"
    settings:
      base:
        INFOPLIST_FILE: "WatchTestWatch Watch App/Info.plist"
        PRODUCT_BUNDLE_IDENTIFIER: ".watchkitapp"
    dependencies:
      - target: "WidgetWatch"

  WidgetWatch:
    platform: watchOS
    deploymentTarget: "9.0"
    type: app-extension
    sources:
      - WidgetWatch
    settings:
      base:
        INFOPLIST_FILE: WidgetWatch/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ".WidgetWatch"
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
